"""empty message

Revision ID: 0e6e56873637
Revises: 
Create Date: 2023-02-08 10:52:49.138445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6e56873637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('Usuario ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario ',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.CHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.CHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.CHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Usuario _pkey')
    )
    op.drop_table('usuario')
    # ### end Alembic commands ###
