"""empty message

Revision ID: 837d2ee5390d
Revises: 
Create Date: 2023-02-13 14:46:13.535347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837d2ee5390d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('provincia')

    # ### end Alembic commands ###
