"""empty message

Revision ID: 1fb5dc26e9d3
Revises: dea94dea5704
Create Date: 2023-03-01 10:56:54.832226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb5dc26e9d3'
down_revision = 'dea94dea5704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=125),
               existing_nullable=False)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=125),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
